//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TweetApp.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChangeFail {
            get {
                return ResourceManager.GetString("ChangeFail", resourceCulture);
            }
        }
        
        internal static string ChangeSuccess {
            get {
                return ResourceManager.GetString("ChangeSuccess", resourceCulture);
            }
        }
        
        internal static string EmailIdExist {
            get {
                return ResourceManager.GetString("EmailIdExist", resourceCulture);
            }
        }
        
        internal static string IncorrectPasswordDetails {
            get {
                return ResourceManager.GetString("IncorrectPasswordDetails", resourceCulture);
            }
        }
        
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        internal static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        internal static string RegistrationUnsuccessful {
            get {
                return ResourceManager.GetString("RegistrationUnsuccessful", resourceCulture);
            }
        }
        
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        internal static string TweetNotPosted {
            get {
                return ResourceManager.GetString("TweetNotPosted", resourceCulture);
            }
        }
        
        internal static string TweetPosted {
            get {
                return ResourceManager.GetString("TweetPosted", resourceCulture);
            }
        }
        
        internal static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
    }
}
